# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#  branches:
#    include:
#      - main

#pr:
#  branches:
#    include:
#      - main

pool: 
  name: Avivapool

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(d5109ab4-ace9-4590-b959-7f015acb7147)'
    KeyVaultName: 'AvivaKeyVault1'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Terraform Plan
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    command: 'plan'
    environmentServiceName: 'Azure subscription 1(d5109ab4-ace9-4590-b959-7f015acb7147)'
    allowTelemetryCollection: false

- task: TerraformCLI@2
  displayName: TerraformDestroy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'destroy'
    environmentServiceName: 'Azure subscription 1(d5109ab4-ace9-4590-b959-7f015acb7147)'
    allowTelemetryCollection: true

